default: &default
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>
  frontend_url: <%= ENV.fetch('FRONTEND_URL') %>
  frontend_email_confirmed_url: <%= ENV.fetch('FRONTEND_URL') + '/email_confirmed' %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
